# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: required
cache: packages

r_github_packages:
  - r-lib/pkgdown

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
