---
title: "The QQ plot"
author: "Manuel Gimond"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: TRUE
    css: style.css
vignette: >
  %\VignetteIndexEntry{The QQ plot}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#> ",
  message = FALSE,
  tidy = FALSE,
  cache = FALSE,
  warning = FALSE,
  encoding = "UTF-8"
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Introduction

The *empirical quantile-quantile plot* (QQ plot) is probably one of the most underused and least appreciated plots in univariate analysis. 


## A working example

```{r}
old <- wat95$avg # legacy temperature normals
new <- wat05$avg # current temperature normals
out <- eda_qq(old, new, md = TRUE)
```

```{r}
labs <- c("low", "mid", "high")
out$avg <- (out$x + out$y) / 2
out <- as.data.frame(out[c(1:2,6)])
out2 <- split(out, cut(avg, c(min(avg), 35, 50, max(avg)), labels = labs, include.lowest = TRUE))
eda_qq(out2$mid$x, out2$mid$y, md = T)

OP <- par(mfrow = c(1,3))
sapply(labs, FUN = \(x) {eda_qq(out2[[x]]$x, out2[[x]]$y ,
                               xlab = "old", ylab = "new", md = T); title(x)} )
par(OP)

```




```{r}
labs <- c("low", "mid", "high")
old.split <- split(old, cut(old, c(min(old), 35, 50, max(old)), labels = labs, include.lowest = TRUE))
new.split <- split(new, cut(new, c(min(new), 35, 50, max(new)), labels = labs, include.lowest = TRUE))


OP <- par(mfrow = c(1,3))
sapply(labs, FUN = \(x) {eda_qq(old.split[[x]], new.split[[x]] ,
                               xlab = "old", ylab = "new", md = T); title(x)} )
par(OP)
```
